#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD

import argparse
import pathlib

import saxonche

ap = argparse.ArgumentParser()
ap.add_argument("file")
ap.add_argument("-s", "--secure", action="store_true", help="Prevent XXE vulnerabilities")
args = ap.parse_args()

c = pathlib.Path(args.file).read_text()

with saxonche.PySaxonProcessor(license=False) as proc:
    if args.secure:
        proc.set_configuration_property("http://saxon.sf.net/feature/allowedProtocols", "")
    xsltproc = proc.new_xslt30_processor()
    document = proc.parse_xml(xml_text=c)
    print(document)
