#!/bin/bash
# SPDX-License-Identifier: 0BSD

MYDIR="$(dirname "$0")"

if [ -z "$1" ]; then
	echo "Usage:"
	echo -e "\t$0 [host] [file path (optional)]"
	exit 1
fi

if [ -e "$1" ]; then
	echo "$1 already exists"
	exit 1
fi

mkdir "$1"
cp -r "$MYDIR"/{local,online} "$1"

sed -i -e "s:bxxe.example.com:$1:g" "$1"/local/bxxe*.xml "$1"/online/bxxe*.dtd
if [ -n "$2" ]; then
	sed -i -e "s:/tmp/secret.txt:$2:g" "$1/online/bxxe.dtd"
fi
